#!/usr/bin/env php
<?php

ini_set('error_reporting', E_ALL);
ini_set('display_errors', '1');
ini_set('display_startup_errors', '1');

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

define('STATAMIC_HOME_PATH', $_SERVER['HOME'].'/.statamic');

$app = new Symfony\Component\Console\Application('Statamic CLI Tool', '1.0');
$app->add(new Statamic\Cli\NewCommand);
$app->add(new Statamic\Cli\UpdateCommand);
$app->add(new Statamic\Cli\VersionCommand);

$app->run();
